### ISSUE TITLE
Multi-line strings for formulas in generated model classes

### ISSUE THREAD

**Issue by tkutcher** [tkutcher/quickbase-client#38]
Formulas with newline characters are output on multiple lines when running `qbc run model-generate`, but they are not enclosed in multiline strings, thus making them invalid python files. Should just need to enclose them in triple quoted strings.

Also while dealing with styling, add an extra newline before the class declaration.

**Comment by mklaber** [comment]
Other than for knowing that a given field [is a formula](https://github.com/tkutcher/quickbase-client/blob/dev/src/quickbase_client/orm/field.py#L97), what is the reason for even storing the formula definition in code?

**Comment by tkutcher** [comment]
> Other than for knowing that a given field [is a formula](https://github.com/tkutcher/quickbase-client/blob/dev/src/quickbase_client/orm/field.py#L97), what is the reason for even storing the formula definition in code?

Good question. A few reasons for my initial interest in storing formulas in the model.

- With the XML API you can actually make a request to edit/update a formula. So we could theoretically have the QuickbaseTableClient/QuickbaseClient interface to that API and support python methods to manipulate formulas and use QuickbaseField objects there. Hypothetical psuedocode:
```py
my_field = SomeTable.schema.some_field
my_field.set_formula('[Other Field] + 1')
my_client.update_field(my_field)
```

- There might be use cases for [this API](https://developer.quickbase.com/operation/runFormula) so it is probably beneficial to have it stored in the model.


You can check out [this project](https://youtu.be/1kkgkx4a2Go) which is a use case of some general formula manipulation/storage through the API,

But I do see a case for how it could clog up the python code. Maybe an option to not pull formulas would be worth it too.

**Comment by mklaber** [comment]
I kinda figured as much. Probably worth eventually hiding it behind a feature flag at least until then.
