### ISSUE TITLE
Bug: can't clear values on update

### ISSUE THREAD

**Issue by mklaber** [tkutcher/quickbase-client#46]
**Describe the bug**

When updating a record, I want to be able to clear out an existing value without clearing out any value not explicitly set. As it stands, the serialisation step omits any fields that have been explicitly set to `None`.

**To Reproduce**

Let's assume you have a `GitHubIssue` that has already been added to QB. And it has Record ID# 5. When you inserted it in to QB, it was labeled with `bug`. Now, the GH user is not so sure and removes all labels.

```python
issue = GitHubIssue(recordid=5, labels=None)
client = GitHubIssue.client(os.environ['QB_USER_TOKEN'])

response = client.add_records(issues, merge_field_id=GitHubIssue.recordid.fid)
```

**Expected behavior**

I would expect our `labels` field to be empty and our `title`, `description`, etc. to be populated as they were before.

**Screenshots**

n/a

**Additional context**

I believe the issue is that the `RecordJsonSeralizer` is checking for `None` [here](https://github.com/tkutcher/quickbase-client/blob/46484be170004bf299ae49d9df6ec6df182b367d/src/quickbase_client/orm/serialize.py#L43) and therefore excluding it from the request that's sent to QB. The solution is likely somehow tracking what attributes of a `QuickBaseTable` get set (regardless of the value they are set to).

**Comment by mklaber** [comment]
@tkutcher what do you think of something like:

```diff
diff --git a/src/quickbase_client/orm/serialize.py b/src/quickbase_client/orm/serialize.py
index 7c188c6..8ae7f9d 100644
--- a/src/quickbase_client/orm/serialize.py
+++ b/src/quickbase_client/orm/serialize.py
@@ -38,9 +38,9 @@ class RecordJsonSerializer(RecordSerializer):
         self.table_cls = table_cls
 
     def serialize(self, record: 'QuickBaseTable') -> Dict:
-        o = {}
+        o = {}            
         for attr, v in record.__dict__.items():
-            if attr[0] == '_' or v is None:
+            if attr[0] == '_' or (v is None and not v in record.__touched_attrs__):
                 continue
             field_info = record.get_field_info(attr)
             o[field_info.fid] = {'value': v}
diff --git a/src/quickbase_client/orm/table.py b/src/quickbase_client/orm/table.py
index 79eff49..b34553a 100644
--- a/src/quickbase_client/orm/table.py
+++ b/src/quickbase_client/orm/table.py
@@ -37,6 +37,7 @@ class QuickBaseTableMeta(type):
         attrs['__mappings__'] = mappings
         attrs['__fidmap__'] = fidmap
         attrs['__schema__'] = _schema
+        attrs['__touched_attrs__'] = set()
         return type.__new__(mcs, name, bases, attrs)
 
     @property
@@ -72,6 +73,13 @@ class QuickBaseTable(metaclass=QuickBaseTableMeta):
         for name, _ in kwargs.items():  # simple way to get the kwarg name if not empty
             raise AttributeError(f'no attribute named {name}')
 
+        # reset the touched attrs now that we have set them all
+        self.__touched_attrs__ = set()
+
+    def __setattr__(self, name: str, value):
+        super().__setattr__(name, value)
+        self.__touched_attrs__.add(name)
+
     @classmethod
     def app_id(cls) -> str:
         """Alias to the app's ID."""

```

(I don't dunder much so not sure if this is the right approach...)

**Comment by tkutcher** [comment]
Hmmmm... so I am trying to figure out how to "clear" a field through the Quickbase API. It looks like it is returning a 400 for me if I pass `null` in the JSON for any field value. I think what you'd have to do is pass the default/empty thing based on the type (i.e., `''` for any text-based-field). If we took the approach that a user specifying some attribute `=None` means to "reset" that field, I think we'd have to implement something where we look at the type and set it to something based on that. Which I am not sure is worth it and the best way to be explicit about the intent in your example would just be to create the object like 

```py
issue = GitHubIssue(recordid=5, labels='')
```

Unless there is something I am missing in the API which I am happy to take another look. My thinking to implement (before I realized I wasn't sure what quickbase would do with a null) was to have some default object like `QB_NONE = object()` that fields get defaulted to, and the serializer skips anything where `v is None`

**Comment by mklaber** [comment]
Ah, I committed the cardinal sin of Quickbase: I assumed their new REST API would behave in a thoughtful manner. Instead, it sounds like it's yet another crapshoot.

If they ever fix their API, we could re-open this issue. But I won't hold my breath.
