### ISSUE TITLE
Cannot get the record ID

### ISSUE THREAD

**Issue by gallarotti** [tkutcher/quickbase-client#51]
**Describe the bug**
My code is very simple
```
project_client = Project.client(TOKEN)
recs = project_client.query()
for r in recs:
    print(r.recordid)
```
the `recordid` is always `null`

The class generated by `qbc` contains the recordid defined as a number:

```
class Project(QuickBaseTable):
    __dbid__ = 'xxxxxxxxx'
    __app__ = ItsmanagementDashboard
    
    date_created = QuickBaseField(fid=1, field_type=Qb.DATETIME)
    date_modified = QuickBaseField(fid=2, field_type=Qb.DATETIME)
    recordid = QuickBaseField(fid=3, field_type=Qb.NUMERIC)
    record_owner = QuickBaseField(fid=4, field_type=Qb.USER)
    last_modified = QuickBaseField(fid=5, field_type=Qb.USER)
```

I even tried to get the record by its record ID, and it worked fine, but the recordid field is None. The following code:

```
project_client = Project.client(TOKEN)
project_schema = Project.schema
q1 = eq_(project_schema.recordid, 1)
r = project_client.query(q1)
print(r[0].recordid)
```
prints `None` on the screen.

How can I get the record ID?

Thanks,
// Francesco

**Comment by tkutcher** [comment]
Hi there - hmmm, for debugging you could try passing `raw=True` and see what data is actually coming back from the Quickbase API. Do you not have a Record ID field in that Project table?

```py
project_client = Project.client(TOKEN)
print(project_client.query(raw=True))
```

**Comment by gallarotti** [comment]
Thanks for the quick reply!
Yes, the field is there on all tables:

<img width="394" alt="image" src="https://user-images.githubusercontent.com/3496428/163258662-bbb8d6f7-17af-42bc-8eb8-8498448b115d.png">

but the raw.text JSON returned by the server does not include field_id 3 - however the field is there because I can query by it:

```
project_client = Project.client(TOKEN)
project_schema = Project.schema
q1 = eq_(project_schema.recordid, 1)
r = project_client.query(q1)
print(r[0].recordid)
```

I really love the work you did on this integration and would love to be able to use it.

Thanks,
// Francesco

**Comment by tkutcher** [comment]
Sure thing! I am a little rusty on parts of this - but I think what you are running in to is that if you do not explicitly specify the fields to return, by default Quickbase will only return the fields that are part of the "default columns". My guess is somehow that field is not specified as a default column and thus why it is coming up as null.

Currently, you could do something like this (and I am realizing some usability/convenience gaps in the library - maybe the library should add a few changes to make this a tad easier):

```py
project_client = Project.client(TOKEN)
q = QuickBaseQuery(where=None, select=[3, 4, 5])
recs = project_client.query(QuickBaseQuery(where=None, select=[3, 4, 5]))
# now each rec should have data for recordid, and whatever fields 4 & 5 are
```

The `where=None` means don't do any query criteria, just grab all records, and the `select=[3,4,5]` means select/return fields 3, 4, & 5

Let me know if you have any luck with that

**Comment by gallarotti** [comment]
Brilliant! No need to change the code, then.
All I had to do was to ensure that the "Add this field to all new reports" checkbox is checked on the Record ID# field - it was unchecked (and probably always is for all built-in fields)

<img width="545" alt="image" src="https://user-images.githubusercontent.com/3496428/163273314-073906e3-4fb9-4d85-9d08-49098479872d.png">

Thanks a lot for your help!!! 

Not related to this, but I couldn't find any reference in the documentation how to change the record owner using your module - can you point me to the right place or for that I need to use the raw API?

**Comment by tkutcher** [comment]
Aha - nice! 

And gotcha - so you can still use this library for something like that, you would just have to go through the lower-level [`QuickBaseApiClient`](https://quickbase-client.readthedocs.io/en/latest/api_reference/client.html#quickbaseapiclient) class (because currently I don't believe there is any integration for setting a "User" value).

But basically you would need to call `add_records` with a record that matches on the record ID and sets the proper user ID for the record owner field (which looks like it is always field ID 4). So something like:

```py

def change_owner(record_id, new_owner_user_id):
    client = QuickBaseApiClient(USER_TOKEN, "foo.quickbase.com")
    client.add_records(
        table_id="thetabledbid",
        data=[
            {
                "3": {"value": record_id},
                "4": {"value": { "id": new_owner_user_id}
            }
        ]
    )
```

Quickbase specifies how to submit data for a User object [here](https://developer.quickbase.com/fieldInfo) (if you scroll down to User), and the add records a API is [here](https://developer.quickbase.com/operation/upsert) if you scroll down to update existing.

Hope this helps! Any other questions let me know. I will go ahead and close this issue but feel free to follow up if needed. 

You did give me some ideas for more features to add in the future!

**Comment by gallarotti** [comment]
That won't work, because built-in values cannot be changed.
You get this error:
`
'{"data":[],"metadata":{"createdRecordIds":[],"lineErrors":{"1":["Can not change the value of the built-in field with ID \\"4\\"."]},"totalNumberOfRecordsProcessed":1,"unchangedRecordIds":[],"updatedRecordIds":[]}}'`

Which is why the QB API has a special method for this, which is API_ChangeRecordOwner - I don't think you have implemented this in your QuickBaseApiClient class

**Comment by tkutcher** [comment]
@gallarotti Ah interesting ok - I don't quite see that in the new Quickbase JSON APIs, seems that one we'd have to go through the old XML APIs. For now I'd say that one will have to be done manually. Though I think there is certainly some value in getting the library able to make some XML API requests for lingering things like this. I'll get that functionality out at some point but for now yea that will have to be done manually.

**Comment by tkutcher** [comment]
@gallarotti just an FYI I pushed some changes today to get things updated and I went ahead and added some simple support for the old Quickbase XML API. This is published in 0.5.1. I added a method for the editing record owner (because I feel that is pretty useful) but can add more pretty easily if more things come up. You can check out the new docs here: https://quickbase-client.readthedocs.io/en/latest/api_reference/client.html#quickbaselegacyapiclient

**Comment by gallarotti** [comment]
Hi Tim, thanks for the update, I will check it out soon. Sorry for the delay but I am off this week.

**Comment by gallarotti** [comment]
@tkutcher Good morning :)
Can this the recent changes be used to create a new user without having to invoke the xml api manually?

**Comment by tkutcher** [comment]
Hi @gallarotti - So the way to talk to the XML API through this library is via the new `QuickbaseLegacyApiClient` class. Which you can actually get to it through the table client and regular client (`my_table_client.api.legacy_api`). You can call `make_request`. If you check out the source for `change_record_owner` (https://github.com/tkutcher/quickbase-client/blob/main/src/quickbase_client/client/legacy_client.py#L80) you'll see an example of how to do it. 

Are you talking about the API_ProvisionUser? I can get that in to the library eventually. But for now if you want to do it manually that might be best so you can cover your exact use cases for adding users. If you want to add a method in QuickbaseLegacyApiClient that covers it I would be happy to accept a merge request with it! Let me know if you have any other questions
