### ISSUE TITLE
Missing return statement for QuickbaseLegacyApiClient.make_request() in legacy_client.py

### ISSUE THREAD

**Issue by sanelson** [tkutcher/quickbase-client#63]
First I'd just like to say thank you so much for creating this wonderful library!! It has been a huge time saver for our team when working with the Quickbase API.

**Describe the bug**
Was trying to query the legacy Quickbase API to call the API_GetSchema action for a table. Tried to check the expected Response object for status and got a "AttributeError: 'NoneType' object has no attribute 'status'" exception. I then realized there was no explicit return statement for the make_request method.

**To Reproduce**
1. Call QuickbaseLegacyApiClient.make_request() method and inspect return value.
2. Return value is None due to no explicit return statement

**Expected behavior**
The QuickbaseLegacyApiClient.make_request() method should return a requests Response object.

**Additional context**
I have fixed the bug in my fork and added a test to check the fix.

**Comment by tkutcher** [comment]
Thanks for spotting this and making the patch! Merged and patched this as 0.6.3, it should be out there now

**Comment by sanelson** [comment]
Awesome, thank you!
